### PR TITLE
[gemspec] cleanup dependencies

### PR DESCRIPTION
**Pull request by mikz**
rack, cuba, celluloid, ... are pulled from airplay gem
no need to lock their versions here

fixes:
```
$ gem install airplayer
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: airplayer requires reel (= 0.4.0), reel-rack (= 0.1.0), celluloid (= 0.15.2); airplay requires celluloid (>= 0.17.0), reel (~> 0.5.0), reel-rack (~> 0.2.2); celluloid-io requires celluloid (>= 0.15.0)
```

### CODE REVIEW

**Comment by mikz** [comment]
Unfortunately it looks like with newer celluloid it can't find my apple tv.
But the airplay gem does not work either.

**Comment by Tomohiro** [comment]
Thanks.

> Unfortunately it looks like with newer celluloid it can't find my apple tv.

I've got the same error on my environment.

Your branch:

```sh
$ git checkout -b mikz-dependencies master
$ git pull https://github.com/mikz/airplayer.git dependencies
$ bundle
$ bundle exec airplayer devices  # Can't find Apple TV
```

airplay-cli:

```sh
$ gem install airplay-cli  # This installs `air` command
$ air list                          # Can't find Apple TV
```

So, I'm going to investigate what caused this...

**Comment by Tomohiro** [comment]
I think airplay's dependencies are broken. Hence I'd like to locking version of dependencies for a while.

Thus this PR is closing for now.

**Comment by mikz** [comment]
@Tomohiro then `airplayer` has to use [`gem`](http://ruby-doc.org/stdlib-1.9.3/libdoc/rubygems/rdoc/Kernel.html#method-i-gem) to lock the correct versions before requiring them.
Because if there is no `gem` locking the version, it will just use the latest one installed, regardless what you have in the gemspec.

**Pull request closed without merging**
